IDIR = inc
CC=gcc
CFLAGS=-ggdb -I$(IDIR) -Wall -std=c99

SRCDIR = src
ODIR = obj
LDIR = lib

LIBS=-lm -lpthread

_DEPS = config.h message.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = server.o message.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: $(SRCDIR)/%.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

server: $(OBJ)
	gcc -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f server $(ODIR)/*.o *~ core $(INCDIR)/*~ 
